---
- name: Copy file into Docker container and execute command
  hosts: local
  become: true
  vars:
    container_name: "dispatch"            # The name of the Docker container
    src_tzupdater: "tzupdater.jar"        # The source path for tzupdater.jar
    src_tzdata: "tzdata2024a.tar.gz"      # The source path for tzdata2019c.tar.gz
    dest_dir: "/home/support"             # Destination directory inside the host
    container_dest_dir: "/tmp"            # Destination directory inside the container

  tasks:

    - name: Get the container ID of the running Docker container
      shell: docker ps -qf "name={{ container_name }}"
      register: container_id
      changed_when: false

    - name: Copy tzupdater.jar to the host
      copy:
        src: "{{ src_tzupdater }}"
        dest: "{{ dest_dir }}/{{ src_tzupdater }}"

    - name: Copy {{ src_tzdata }} to the host
      copy:
        src: "{{ src_tzdata }}"
        dest: "{{ dest_dir }}/{{ src_tzdata }}"

    - name: Copy tzupdater.jar into Docker container {{ container_id.stdout }}
      shell: docker cp {{ dest_dir }}/{{ src_tzupdater }} {{ container_id.stdout }}:{{ container_dest_dir }}/

    - name: Copy {{ src_tzdata }} into Docker container {{ container_id.stdout }}
      shell: docker cp {{ dest_dir }}/{{ src_tzdata }} {{ container_id.stdout }}:{{ container_dest_dir }}/

    - name: Execute Java command in Docker container {{ container_id.stdout }}
      shell: docker exec -it {{ container_id.stdout }} sh -c "java -jar {{ container_dest_dir }}/{{ src_tzupdater }} -v -f -l file:{{ container_dest_dir }}/{{ src_tzdata }}"
