---
- name: Copy file into Docker container and execute command
  hosts: local 
  become: true  
  tasks:

    - name: Get the container ID of the running Docker container
      shell: docker ps -qf "name=dispatch"
      register: container_id
      changed_when: false

    - name: Copy tzupdater.jar to the Docker container
      copy:
        src: files/tzupdater.jar
        dest: /home/support/tzupdater.jar

    - name: Copy tzdata2019c.tar.gz to the Docker container {{container_id}}
      copy:
        src: files/tzdata2019c.tar.gz
        dest: /home/support/tzdata2019c.tar.gz

    - name: copy tzdata into container {{container_id}}
      shell: docker cp /home/support/tzupdater.jar {{container_id}}:/tmp/
   
    - name: copy tzdata into container {{container_id}}
      shell: docker cp /home/support/tzdata2019c.tar.gz {{container_id}}:/tmp/
    
    - name: Execute Java command in Docker container {{container_id}}
      shell: docker exec -it {{container_id}} sh -c "java -jar /tmp/tzupdater.jar -v -f -l file:/tmp/tzdata2019c.tar.gz"
